## EDA - oscars data

In [759]:
import pandas as pd

read csv file

In [760]:
oscars = pd.read_csv('../data/raw/unclean_oscars.csv')

get some info about oscars data

In [761]:
oscars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12014 entries, 0 to 12013
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ceremony             12014 non-null  int64
 1   award_year           12014 non-null  object
 2   award_class          12014 non-null  object
 3   canonical_category   12014 non-null  object
 4   category             12014 non-null  object
 5   nom_id               11482 non-null  object
 6   film                 10753 non-null  object
 7   film_id              10753 non-null  object
 8   Name                 10829 non-null  object
 9   nominees             11661 non-null  object
 10  nominee_ids          11134 non-null  object
 11  winner               12014 non-null  bool
 12  detail               3171 non-null   object
 13  multifilmnomination  12014 non-null  bool
dtypes: bool(2), int64(1), object(11)
memory usage: 1.1+ MB

In [762]:
oscars.head()

,ceremony,award_year,award_class,canonical_category,category,nom_id,film,film_id,Name,nominees,nominee_ids,winner,detail,multifilmnomination
0,1,1927/28,Acting,ACTOR IN A LEADING ROLE,ACTOR,an0051251,The Noose,tt0019217,Richard Barthelmess,Richard Barthelmess,nm0001932,False,Nickie Elkins,True
1,1,1927/28,Acting,ACTOR IN A LEADING ROLE,ACTOR,an0051252,The Patent Leather Kid,tt0018253,Richard Barthelmess,Richard Barthelmess,nm0001932,False,The Patent Leather Kid,True
2,1,1927/28,Acting,ACTOR IN A LEADING ROLE,ACTOR,an0051250a,The Last Command,tt0019071,Emil Jannings,Emil Jannings,nm0417837,True,General Dolgorucki [Grand Duke Sergius Alexander],True
3,1,1927/28,Acting,ACTOR IN A LEADING ROLE,ACTOR,an0051250b,The Way of All Flesh,tt0019553,Emil Jannings,Emil Jannings,nm0417837,True,August Schilling,True
4,1,1927/28,Acting,ACTRESS IN A LEADING ROLE,ACTRESS,an0051255,A Ship Comes In,tt0018389,Louise Dresser,Louise Dresser,nm0237571,False,Mrs. Pleznik,False

In [763]:
oscars.shape

(12014, 14)

In [764]:
oscars.isnull().sum()

ceremony                  0
award_year                0
award_class               0
canonical_category        0
category                  0
nom_id                  532
film                   1261
film_id                1261
Name                   1185
nominees                353
nominee_ids             880
winner                    0
detail                 8843
multifilmnomination       0
dtype: int64


### detail → many nulls but useful context → fillna("None")

### need to fillna for some otehr columns too

In [765]:
oscars['multifilmnomination'].value_counts()

multifilmnomination
False    11974
True        40
Name: count, dtype: int64

### multifilmnomiation only has 40 true - column doesnt infer much - drop

In [766]:
oscars['award_year'].value_counts()

award_year
1942       190
1941       190
1943       188
1944       180
1940       162
          ...
1930/31     50
1931/32     47
1928/29     46
1929/30     46
1927/28     41
Name: count, Length: 97, dtype: int64

In [767]:
oscars['category'].value_counts()

category
DIRECTING                                         476
FILM EDITING                                      455
ACTRESS IN A SUPPORTING ROLE                      445
ACTOR IN A SUPPORTING ROLE                        445
BEST PICTURE                                      381
                                                 ...
DIRECTING (Comedy Picture)                          2
SPECIAL FOREIGN LANGUAGE FILM AWARD                 2
SCIENTIFIC AND TECHNICAL AWARD (Special Award)      1
SPECIAL ACHIEVEMENT AWARD (Sound Editing)           1
SPECIAL ACHIEVEMENT AWARD (Sound Effects)           1
Name: count, Length: 128, dtype: int64

In [768]:
oscars['canonical_category'].value_counts()

canonical_category
BEST PICTURE                                      611
MUSIC (Original Score)                            524
ACTRESS IN A LEADING ROLE                         484
WRITING (Adapted Screenplay)                      482
ACTOR IN A LEADING ROLE                           481
                                                 ...
DIRECTING (Comedy Picture)                          2
SPECIAL FOREIGN LANGUAGE FILM AWARD                 2
SPECIAL ACHIEVEMENT AWARD (Sound Editing)           1
SPECIAL ACHIEVEMENT AWARD (Sound Effects)           1
SCIENTIFIC AND TECHNICAL AWARD (Special Award)      1
Name: count, Length: 65, dtype: int64

In [769]:
oscars['award_class'].value_counts()

award_class
Production    3257
Title         2748
Acting        1855
Music         1322
Writing       1032
SciTech        904
Directing      516
Special        380
Name: count, dtype: int64

In [770]:
oscars['winner'].value_counts()

winner
False    8538
True     3476
Name: count, dtype: int64

how many duplicates are there?

In [771]:
duplicates = oscars.duplicated().sum()
print(f'There are {duplicates} duplicate rows in the Oscars DataFrame.')

There are 1 duplicate rows in the Oscars DataFrame.

In [772]:
unique_date_formats = oscars['award_year'].unique()
print(f'Different date formats in oscars: {unique_date_formats[:20]}')

Different date formats in oscars: ['1927/28' '1928/29' '1929/30' '1930/31' '1931/32' '1932/33' '1934' '1935'
 '1938' '1936' '1937' '2007' '1939' '1940' '1941' '1942' '1943' '1944'
 '1945' '1946']

### firstly the award_year col is a string not datetime 
### also, some entries have two years for award_year

### why do some nominations not have a film or name associated with them?

In [773]:
oscars[oscars['film'].isnull()].head(10)

,ceremony,award_year,award_class,canonical_category,category,nom_id,film,film_id,Name,nominees,nominee_ids,winner,detail,multifilmnomination
22,1,1927/28,Production,VISUAL EFFECTS,ENGINEERING EFFECTS,an0051285,NaN,NaN,Ralph Hammeras,Ralph Hammeras,nm0358518,False,NaN,False
24,1,1927/28,Production,VISUAL EFFECTS,ENGINEERING EFFECTS,an0051284,NaN,NaN,Nugent Slaughter,Nugent Slaughter,nm0805521,False,NaN,False
37,1,1927/28,Writing,WRITING (Title Writing),WRITING (Title Writing),an0051269,NaN,NaN,Joseph Farnham,Joseph Farnham,nm0267868,True,NaN,False
38,1,1927/28,Writing,WRITING (Title Writing),WRITING (Title Writing),an0051270,NaN,NaN,"George Marion, Jr.",George Marion Jr.,nm0547938,False,NaN,False
163,4,1930/31,Production,SOUND RECORDING,SOUND RECORDING,an0050118,NaN,NaN,Samuel Goldwyn - United Artists Studio Sound D...,Samuel Goldwyn - United Artists,co0026841,False,NaN,False
164,4,1930/31,Production,SOUND RECORDING,SOUND RECORDING,an0050116,NaN,NaN,Metro-Goldwyn-Mayer Studio Sound Department,Metro-Goldwyn-Mayer,co0007143,False,NaN,False
165,4,1930/31,Production,SOUND RECORDING,SOUND RECORDING,an0050115,NaN,NaN,Paramount Publix Studio Sound Department,Paramount Publix,co0023400,True,NaN,False
166,4,1930/31,Production,SOUND RECORDING,SOUND RECORDING,an0050117,NaN,NaN,RKO Radio Studio Sound Department,RKO Radio,co0041421,False,NaN,False
177,4,1930/31,SciTech,SCIENTIFIC OR TECHNICAL AWARD (Class I),SCIENTIFIC OR TECHNICAL AWARD (Class I),NaN,NaN,NaN,NaN,"ELECTRICAL RESEARCH PRODUCTS INC., RCA-PHOTOPH...",NaN,True,Sound,False
178,4,1930/31,SciTech,SCIENTIFIC OR TECHNICAL AWARD (Class I),SCIENTIFIC OR TECHNICAL AWARD (Class I),NaN,NaN,NaN,NaN,"DuPONT FILM MANUFACTURING CORP., Eastman Kodak...",NaN,True,Film,False

In [774]:
oscars[oscars['film'].isnull()].tail(10)

,ceremony,award_year,award_class,canonical_category,category,nom_id,film,film_id,Name,nominees,nominee_ids,winner,detail,multifilmnomination
12004,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Scientific and...,SCIENTIFIC AND TECHNICAL AWARD (Scientific and...,NaN,NaN,NaN,NaN,"Steve Wagner, Garrett Brown, Jerry Holway, Rob...",NaN,True,NaN,False
12005,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Scientific and...,SCIENTIFIC AND TECHNICAL AWARD (Scientific and...,NaN,NaN,NaN,NaN,Dave Freeth,NaN,True,NaN,False
12006,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,"Essex Edwards, James Jacobs, Jernej Barbic, Cr...",NaN,True,NaN,False
12007,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,"Javor Kalojanov, Kimball Thurston",NaN,True,NaN,False
12008,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,Neeme Vaino,NaN,True,NaN,False
12009,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,"Dustin Brooks, Colin Decker",NaN,True,NaN,False
12010,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,"Attila T. Áfra, Timo Aila",NaN,True,NaN,False
12011,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,Mark Noel,NaN,True,NaN,False
12012,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,"Su Tie, Bei Shimen, Zhao Yanchong",NaN,True,NaN,False
12013,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,"Tabb Firchau, John Ellison, Steve Webb, David ...",NaN,True,NaN,False

In [775]:
oscars[oscars['Name'].isnull()].head(10)

,ceremony,award_year,award_class,canonical_category,category,nom_id,film,film_id,Name,nominees,nominee_ids,winner,detail,multifilmnomination
39,1,1927/28,Special,SPECIAL AWARD,SPECIAL AWARD,an0051420,The Jazz Singer,tt0018037,NaN,Warner Bros.,co0080422,True,NaN,False
40,1,1927/28,Special,SPECIAL AWARD,SPECIAL AWARD,an0051421,The Circus,tt0018773,NaN,Charles Chaplin,nm0000122,True,NaN,False
177,4,1930/31,SciTech,SCIENTIFIC OR TECHNICAL AWARD (Class I),SCIENTIFIC OR TECHNICAL AWARD (Class I),NaN,NaN,NaN,NaN,"ELECTRICAL RESEARCH PRODUCTS INC., RCA-PHOTOPH...",NaN,True,Sound,False
178,4,1930/31,SciTech,SCIENTIFIC OR TECHNICAL AWARD (Class I),SCIENTIFIC OR TECHNICAL AWARD (Class I),NaN,NaN,NaN,NaN,"DuPONT FILM MANUFACTURING CORP., Eastman Kodak...",NaN,True,Film,False
179,4,1930/31,SciTech,SCIENTIFIC OR TECHNICAL AWARD (Class II),SCIENTIFIC OR TECHNICAL AWARD (Class II),NaN,NaN,NaN,NaN,Fox Film Corp.,NaN,True,Sound,False
180,4,1930/31,SciTech,SCIENTIFIC OR TECHNICAL AWARD (Class III),SCIENTIFIC OR TECHNICAL AWARD (Class III),NaN,NaN,NaN,NaN,Electrical Research Products Inc.,NaN,True,Sound,False
181,4,1930/31,SciTech,SCIENTIFIC OR TECHNICAL AWARD (Class III),SCIENTIFIC OR TECHNICAL AWARD (Class III),NaN,NaN,NaN,NaN,Rko Radio Pictures,NaN,True,Sound,False
182,4,1930/31,SciTech,SCIENTIFIC OR TECHNICAL AWARD (Class III),SCIENTIFIC OR TECHNICAL AWARD (Class III),NaN,NaN,NaN,NaN,Rca-Photophone Inc.,NaN,True,Sound,False
228,5,1931/32,Special,SPECIAL AWARD,SPECIAL AWARD,an0051402,NaN,NaN,NaN,Walt Disney,nm0000370,True,NaN,False
229,5,1931/32,SciTech,SCIENTIFIC OR TECHNICAL AWARD (Class II),SCIENTIFIC OR TECHNICAL AWARD (Class II),NaN,NaN,NaN,NaN,Technicolor Motion Picture Corp.,NaN,True,Cartoon Process,False

In [776]:
oscars[oscars['Name'].isnull()].tail(10)

,ceremony,award_year,award_class,canonical_category,category,nom_id,film,film_id,Name,nominees,nominee_ids,winner,detail,multifilmnomination
12004,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Scientific and...,SCIENTIFIC AND TECHNICAL AWARD (Scientific and...,NaN,NaN,NaN,NaN,"Steve Wagner, Garrett Brown, Jerry Holway, Rob...",NaN,True,NaN,False
12005,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Scientific and...,SCIENTIFIC AND TECHNICAL AWARD (Scientific and...,NaN,NaN,NaN,NaN,Dave Freeth,NaN,True,NaN,False
12006,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,"Essex Edwards, James Jacobs, Jernej Barbic, Cr...",NaN,True,NaN,False
12007,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,"Javor Kalojanov, Kimball Thurston",NaN,True,NaN,False
12008,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,Neeme Vaino,NaN,True,NaN,False
12009,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,"Dustin Brooks, Colin Decker",NaN,True,NaN,False
12010,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,"Attila T. Áfra, Timo Aila",NaN,True,NaN,False
12011,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,Mark Noel,NaN,True,NaN,False
12012,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,"Su Tie, Bei Shimen, Zhao Yanchong",NaN,True,NaN,False
12013,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,"Tabb Firchau, John Ellison, Steve Webb, David ...",NaN,True,NaN,False

### so the nominations that dont have a film or name associated with them seem to be for a scientific or technical award or special award

# Cleaning

For cleaning, I will have to 
- format date to be only one year and change type to datetime
- group some categories to decrease amount of different categories we have for better analysis
- drop multifilmnomination column
- fill na of some columns 
- change Name column to name to match the conventions of other col names

In [777]:
oscars = oscars.rename(columns={"Name": "name"})

In [778]:
def standardise_year(award_year):
    if isinstance(award_year, str):
        award_year = award_year.strip()
        if '/' in award_year:
            parts = award_year.split('/')
            if len(parts) == 2:
                base = parts[0][:2]
                year = int(base + parts[1])
                return pd.to_datetime(str(year), format='%Y')
        elif '/' not in award_year:
            return pd.to_datetime(award_year, format='%Y')

    return pd.NaT

In [779]:
oscars['award_year'] = oscars['award_year'].apply(standardise_year).dt.year
oscars.dtypes

ceremony                int64
award_year              int32
award_class            object
canonical_category     object
category               object
nom_id                 object
film                   object
film_id                object
name                   object
nominees               object
nominee_ids            object
winner                   bool
detail                 object
multifilmnomination      bool
dtype: object

In [780]:
oscars.head()

,ceremony,award_year,award_class,canonical_category,category,nom_id,film,film_id,name,nominees,nominee_ids,winner,detail,multifilmnomination
0,1,1928,Acting,ACTOR IN A LEADING ROLE,ACTOR,an0051251,The Noose,tt0019217,Richard Barthelmess,Richard Barthelmess,nm0001932,False,Nickie Elkins,True
1,1,1928,Acting,ACTOR IN A LEADING ROLE,ACTOR,an0051252,The Patent Leather Kid,tt0018253,Richard Barthelmess,Richard Barthelmess,nm0001932,False,The Patent Leather Kid,True
2,1,1928,Acting,ACTOR IN A LEADING ROLE,ACTOR,an0051250a,The Last Command,tt0019071,Emil Jannings,Emil Jannings,nm0417837,True,General Dolgorucki [Grand Duke Sergius Alexander],True
3,1,1928,Acting,ACTOR IN A LEADING ROLE,ACTOR,an0051250b,The Way of All Flesh,tt0019553,Emil Jannings,Emil Jannings,nm0417837,True,August Schilling,True
4,1,1928,Acting,ACTRESS IN A LEADING ROLE,ACTRESS,an0051255,A Ship Comes In,tt0018389,Louise Dresser,Louise Dresser,nm0237571,False,Mrs. Pleznik,False

In [781]:
oscars['canonical_category'].value_counts(ascending=True).head(20)

canonical_category
SCIENTIFIC AND TECHNICAL AWARD (Special Award)        1
SPECIAL ACHIEVEMENT AWARD (Sound Effects)             1
SPECIAL ACHIEVEMENT AWARD (Sound Editing)             1
SPECIAL FOREIGN LANGUAGE FILM AWARD                   2
DIRECTING (Comedy Picture)                            2
WRITING (Title Writing)                               3
UNIQUE AND ARTISTIC PICTURE                           3
SPECIAL ACHIEVEMENT AWARD                             3
DIRECTING (Dramatic Picture)                          3
SPECIAL ACHIEVEMENT AWARD (Sound Effects Editing)     4
SHORT SUBJECT (Color)                                 6
SPECIAL ACHIEVEMENT AWARD (Visual Effects)            9
SHORT SUBJECT (Novelty)                              12
AWARD OF COMMENDATION                                13
SHORT SUBJECT (Comedy)                               13
SCIENTIFIC OR TECHNICAL AWARD (Class I)              18
MEDAL OF COMMENDATION                                18
JOHN A. BONNER MEDAL OF COMMENDATION                 20
DANCE DIRECTION                                      24
GORDON E. SAWYER AWARD                               27
Name: count, dtype: int64

In [782]:
oscars['canonical_category'].value_counts(ascending=False).head(30)

canonical_category
BEST PICTURE                                                         611
MUSIC (Original Score)                                               524
ACTRESS IN A LEADING ROLE                                            484
WRITING (Adapted Screenplay)                                         482
ACTOR IN A LEADING ROLE                                              481
MUSIC (Original Song)                                                480
DIRECTING                                                            476
FILM EDITING                                                         455
ACTRESS IN A SUPPORTING ROLE                                         445
ACTOR IN A SUPPORTING ROLE                                           445
WRITING (Original Screenplay)                                        420
SHORT FILM (Animated)                                                398
DOCUMENTARY (Short Subject)                                          393
DOCUMENTARY (Feature)                                                385
ART DIRECTION                                                        374
INTERNATIONAL FEATURE FILM                                           350
CINEMATOGRAPHY                                                       345
SCIENTIFIC AND TECHNICAL AWARD (Technical Achievement Award)         343
SOUND MIXING                                                         335
SHORT FILM (Live Action)                                             302
COSTUME DESIGN                                                       300
MUSIC (Original Song Score or Adaptation Score)                      294
VISUAL EFFECTS                                                       272
SCIENTIFIC AND TECHNICAL AWARD (Scientific and Engineering Award)    237
SOUND RECORDING                                                      195
SCIENTIFIC OR TECHNICAL AWARD (Class III)                            182
CINEMATOGRAPHY (Black-and-White)                                     161
SOUND EDITING                                                        143
ART DIRECTION (Black-and-White)                                      138
MAKEUP AND HAIRSTYLING                                               138
Name: count, dtype: int64

In [783]:
oscars['category'].value_counts(ascending=False).head(30)

category
DIRECTING                                                            476
FILM EDITING                                                         455
ACTRESS IN A SUPPORTING ROLE                                         445
ACTOR IN A SUPPORTING ROLE                                           445
BEST PICTURE                                                         381
DOCUMENTARY (Short Subject)                                          378
CINEMATOGRAPHY                                                       345
DOCUMENTARY (Feature)                                                345
FOREIGN LANGUAGE FILM                                                315
ART DIRECTION                                                        309
COSTUME DESIGN                                                       300
MUSIC (Original Score)                                               275
SCIENTIFIC AND TECHNICAL AWARD (Technical Achievement Award)         254
SOUND                                                                250
ACTRESS IN A LEADING ROLE                                            245
ACTOR IN A LEADING ROLE                                              245
MUSIC (Original Song)                                                240
ACTRESS                                                              239
ACTOR                                                                236
SHORT FILM (Live Action)                                             231
SHORT FILM (Animated)                                                215
MUSIC (Song)                                                         215
SOUND RECORDING                                                      195
SCIENTIFIC OR TECHNICAL AWARD (Class III)                            182
SCIENTIFIC AND TECHNICAL AWARD (Scientific and Engineering Award)    170
SHORT SUBJECT (Cartoon)                                              169
WRITING (Original Screenplay)                                        165
CINEMATOGRAPHY (Black-and-White)                                     161
VISUAL EFFECTS                                                       160
MUSIC (Music Score of a Dramatic or Comedy Picture)                  148
Name: count, dtype: int64

In [784]:
oscars['category'].value_counts(ascending=True).head(30)

category
SPECIAL ACHIEVEMENT AWARD (Sound Editing)                                                  1
SCIENTIFIC AND TECHNICAL AWARD (Special Award)                                             1
SPECIAL ACHIEVEMENT AWARD (Sound Effects)                                                  1
DIRECTING (Comedy Picture)                                                                 2
SPECIAL FOREIGN LANGUAGE FILM AWARD                                                        2
SHORT FILM (Dramatic Live Action)                                                          3
MUSIC (Adaptation Score)                                                                   3
DIRECTING (Dramatic Picture)                                                               3
ENGINEERING EFFECTS                                                                        3
MUSIC (Original Song Score or Adaptation Score)                                            3
UNIQUE AND ARTISTIC PICTURE                                                                3
SPECIAL ACHIEVEMENT AWARD                                                                  3
WRITING (Title Writing)                                                                    3
SPECIAL ACHIEVEMENT AWARD (Sound Effects Editing)                                          4
ANIMATED SHORT FILM                                                                        5
WRITING (Screenplay--Adapted)                                                              5
WRITING (Story and Screenplay--based on material not previously published or produced)     5
WRITING (Screenplay--Original)                                                             5
HONORARY FOREIGN LANGUAGE FILM AWARD                                                       5
SHORT SUBJECT (Color)                                                                      6
MUSIC (Original Song Score and Its Adaptation -or- Adaptation Score)                       6
MUSIC (Original Song Score and Its Adaptation or Adaptation Score)                         6
OUTSTANDING PICTURE                                                                        8
MUSIC (Original Song Score)                                                                8
MUSIC (Scoring: Adaptation and Original Song Score)                                        8
MUSIC (Scoring: Original Song Score and Adaptation -or- Scoring: Adaptation)               9
SPECIAL ACHIEVEMENT AWARD (Visual Effects)                                                 9
SHORT SUBJECT (Animated)                                                                   9
SOUND EFFECTS                                                                             10
MUSIC (Original Score--for a motion picture [not a musical])                              10
Name: count, dtype: int64

In [785]:
oscars = oscars.drop(columns=['multifilmnomination'])
oscars

,ceremony,award_year,award_class,canonical_category,category,nom_id,film,film_id,name,nominees,nominee_ids,winner,detail
0,1,1928,Acting,ACTOR IN A LEADING ROLE,ACTOR,an0051251,The Noose,tt0019217,Richard Barthelmess,Richard Barthelmess,nm0001932,False,Nickie Elkins
1,1,1928,Acting,ACTOR IN A LEADING ROLE,ACTOR,an0051252,The Patent Leather Kid,tt0018253,Richard Barthelmess,Richard Barthelmess,nm0001932,False,The Patent Leather Kid
2,1,1928,Acting,ACTOR IN A LEADING ROLE,ACTOR,an0051250a,The Last Command,tt0019071,Emil Jannings,Emil Jannings,nm0417837,True,General Dolgorucki [Grand Duke Sergius Alexander]
3,1,1928,Acting,ACTOR IN A LEADING ROLE,ACTOR,an0051250b,The Way of All Flesh,tt0019553,Emil Jannings,Emil Jannings,nm0417837,True,August Schilling
4,1,1928,Acting,ACTRESS IN A LEADING ROLE,ACTRESS,an0051255,A Ship Comes In,tt0018389,Louise Dresser,Louise Dresser,nm0237571,False,Mrs. Pleznik
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12009,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,"Dustin Brooks, Colin Decker",NaN,True,NaN
12010,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,"Attila T. Áfra, Timo Aila",NaN,True,NaN
12011,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,Mark Noel,NaN,True,NaN
12012,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,"Su Tie, Bei Shimen, Zhao Yanchong",NaN,True,NaN
12013,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,"Tabb Firchau, John Ellison, Steve Webb, David ...",NaN,True,NaN

### Handling the nulls

In [786]:
oscars.isnull().sum()

ceremony                 0
award_year               0
award_class              0
canonical_category       0
category                 0
nom_id                 532
film                  1261
film_id               1261
name                  1185
nominees               353
nominee_ids            880
winner                   0
detail                8843
dtype: int64

In [787]:
# Get rows where Name is null
oscars[oscars["name"].isna()]

,ceremony,award_year,award_class,canonical_category,category,nom_id,film,film_id,name,nominees,nominee_ids,winner,detail
39,1,1928,Special,SPECIAL AWARD,SPECIAL AWARD,an0051420,The Jazz Singer,tt0018037,NaN,Warner Bros.,co0080422,True,NaN
40,1,1928,Special,SPECIAL AWARD,SPECIAL AWARD,an0051421,The Circus,tt0018773,NaN,Charles Chaplin,nm0000122,True,NaN
177,4,1931,SciTech,SCIENTIFIC OR TECHNICAL AWARD (Class I),SCIENTIFIC OR TECHNICAL AWARD (Class I),NaN,NaN,NaN,NaN,"ELECTRICAL RESEARCH PRODUCTS INC., RCA-PHOTOPH...",NaN,True,Sound
178,4,1931,SciTech,SCIENTIFIC OR TECHNICAL AWARD (Class I),SCIENTIFIC OR TECHNICAL AWARD (Class I),NaN,NaN,NaN,NaN,"DuPONT FILM MANUFACTURING CORP., Eastman Kodak...",NaN,True,Film
179,4,1931,SciTech,SCIENTIFIC OR TECHNICAL AWARD (Class II),SCIENTIFIC OR TECHNICAL AWARD (Class II),NaN,NaN,NaN,NaN,Fox Film Corp.,NaN,True,Sound
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12009,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,"Dustin Brooks, Colin Decker",NaN,True,NaN
12010,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,"Attila T. Áfra, Timo Aila",NaN,True,NaN
12011,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,Mark Noel,NaN,True,NaN
12012,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,"Su Tie, Bei Shimen, Zhao Yanchong",NaN,True,NaN
12013,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,"Tabb Firchau, John Ellison, Steve Webb, David ...",NaN,True,NaN

In [788]:
# oscars = oscars.fillna({'Name': 'Not applicable (Special / SciTech Award)'})

In [789]:
# oscars = oscars.fillna({'film': 'Not applicable (Special / SciTech Award)'})

In [790]:
oscars[oscars["nominees"].isna()].groupby("award_class").size()

award_class
Production      2
SciTech         1
Special         5
Title         345
dtype: int64

In [791]:
oscars[oscars["film"].isna()].groupby("award_class").size()

award_class
Directing      18
Production     10
SciTech       902
Special       329
Writing         2
dtype: int64

In [792]:
oscars[oscars["name"].isna()].groupby("award_class").size()

award_class
Production      2
SciTech       904
Special       274
Title           5
dtype: int64

All nulls in columns - ie nominees for international film -

In [793]:
fill_na_cols = ["name", "film", "nominees", "nominee_ids", "nom_id", "film_id", "detail"]

oscars[fill_na_cols] = oscars[fill_na_cols].fillna("N/A")
oscars

,ceremony,award_year,award_class,canonical_category,category,nom_id,film,film_id,name,nominees,nominee_ids,winner,detail
0,1,1928,Acting,ACTOR IN A LEADING ROLE,ACTOR,an0051251,The Noose,tt0019217,Richard Barthelmess,Richard Barthelmess,nm0001932,False,Nickie Elkins
1,1,1928,Acting,ACTOR IN A LEADING ROLE,ACTOR,an0051252,The Patent Leather Kid,tt0018253,Richard Barthelmess,Richard Barthelmess,nm0001932,False,The Patent Leather Kid
2,1,1928,Acting,ACTOR IN A LEADING ROLE,ACTOR,an0051250a,The Last Command,tt0019071,Emil Jannings,Emil Jannings,nm0417837,True,General Dolgorucki [Grand Duke Sergius Alexander]
3,1,1928,Acting,ACTOR IN A LEADING ROLE,ACTOR,an0051250b,The Way of All Flesh,tt0019553,Emil Jannings,Emil Jannings,nm0417837,True,August Schilling
4,1,1928,Acting,ACTRESS IN A LEADING ROLE,ACTRESS,an0051255,A Ship Comes In,tt0018389,Louise Dresser,Louise Dresser,nm0237571,False,Mrs. Pleznik
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12009,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,N/A,N/A,N/A,N/A,"Dustin Brooks, Colin Decker",N/A,True,N/A
12010,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,N/A,N/A,N/A,N/A,"Attila T. Áfra, Timo Aila",N/A,True,N/A
12011,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,N/A,N/A,N/A,N/A,Mark Noel,N/A,True,N/A
12012,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,N/A,N/A,N/A,N/A,"Su Tie, Bei Shimen, Zhao Yanchong",N/A,True,N/A
12013,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,N/A,N/A,N/A,N/A,"Tabb Firchau, John Ellison, Steve Webb, David ...",N/A,True,N/A

In [794]:
oscars.isnull().sum()

ceremony              0
award_year            0
award_class           0
canonical_category    0
category              0
nom_id                0
film                  0
film_id               0
name                  0
nominees              0
nominee_ids           0
winner                0
detail                0
dtype: int64

In [795]:
oscars.drop_duplicates(inplace=True)

In [796]:
oscars.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12013 entries, 0 to 12013
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ceremony            12013 non-null  int64
 1   award_year          12013 non-null  int32
 2   award_class         12013 non-null  object
 3   canonical_category  12013 non-null  object
 4   category            12013 non-null  object
 5   nom_id              12013 non-null  object
 6   film                12013 non-null  object
 7   film_id             12013 non-null  object
 8   name                12013 non-null  object
 9   nominees            12013 non-null  object
 10  nominee_ids         12013 non-null  object
 11  winner              12013 non-null  bool
 12  detail              12013 non-null  object
dtypes: bool(1), int32(1), int64(1), object(10)
memory usage: 1.2+ MB

# Transform

### creating the new column main_categories

#### right now there are too many categories in canonical_category and category which will not be great for analysis purposes - therefore, i want to create a new column that will group the categories from canonical_category to the main awards most people know - ie best picture, best actor, etc

#### i've used generative AI to help me create this function to map the canonical_category column to main_category

In [797]:
def map_to_main_category(cat: str) -> str:
    cat_upper = str(cat).upper()
    
    # Picture
    if "PICTURE" in cat_upper and "SHORT" not in cat_upper and "ARTISTIC" not in cat_upper:
        return "Best Picture"
    
    # Director
    if "DIRECTING" in cat_upper:
        return "Best Director"
    
    # Acting
    if "ACTOR" in cat_upper and "SUPPORTING" in cat_upper:
        return "Best Supporting Actor"
    if "ACTRESS" in cat_upper and "SUPPORTING" in cat_upper:
        return "Best Supporting Actress"
    if "ACTOR" in cat_upper:
        return "Best Actor"
    if "ACTRESS" in cat_upper:
        return "Best Actress"
    
    # Writing
    if "WRITING" in cat_upper or "SCREENPLAY" in cat_upper:
        if "ADAPTED" in cat_upper:
            return "Best Adapted Screenplay"
        return "Best Original Screenplay"
    
    # Shorts
    if "SHORT" in cat_upper and "DOCUMENTARY" not in cat_upper and "ANIMATED" not in cat_upper:
        return "Best Live-Action Short Film"
    if "ANIMATED SHORT" in cat_upper:
        return "Best Animated Short Film"
    if "DOCUMENTARY SHORT" in cat_upper:
        return "Best Documentary Short Film"
    
    # Documentary
    if "DOCUMENTARY" in cat_upper:
        if "SHORT" in cat_upper:
            return "Best Documentary Short Film"
        return "Best Documentary Feature Film"
    
    # International
    if "FOREIGN" in cat_upper or "INTERNATIONAL" in cat_upper:
        return "Best International Feature Film"
    
    # Music
    if "SCORE" in cat_upper:
        return "Best Original Score"
    if "SONG" in cat_upper:
        return "Best Original Song"
    
    # Craft
    if "CINEMATOGRAPHY" in cat_upper:
        return "Best Cinematography"
    if "EDITING" in cat_upper:
        return "Best Film Editing"
    if "PRODUCTION DESIGN" in cat_upper or "ART DIRECTION" in cat_upper:
        return "Best Production Design"
    if "COSTUME" in cat_upper:
        return "Best Costume Design"
    if "MAKEUP" in cat_upper or "HAIR" in cat_upper:
        return "Best Makeup & Hairstyling"
    if "SOUND" in cat_upper:
        return "Best Sound"
    if "VISUAL EFFECTS" in cat_upper or "SPECIAL EFFECTS" in cat_upper:
        return "Best Visual Effects"
    
    # Animated Feature
    if "ANIMATED FEATURE" in cat_upper or "ANIMATION" in cat_upper:
        return "Best Animated Feature Film"
    
    # Catch-all
    return "Other / Retired"

In [798]:
oscars['main_category'] = oscars['canonical_category'].apply(map_to_main_category)

In [799]:
oscars

,ceremony,award_year,award_class,canonical_category,category,nom_id,film,film_id,name,nominees,nominee_ids,winner,detail,main_category
0,1,1928,Acting,ACTOR IN A LEADING ROLE,ACTOR,an0051251,The Noose,tt0019217,Richard Barthelmess,Richard Barthelmess,nm0001932,False,Nickie Elkins,Best Actor
1,1,1928,Acting,ACTOR IN A LEADING ROLE,ACTOR,an0051252,The Patent Leather Kid,tt0018253,Richard Barthelmess,Richard Barthelmess,nm0001932,False,The Patent Leather Kid,Best Actor
2,1,1928,Acting,ACTOR IN A LEADING ROLE,ACTOR,an0051250a,The Last Command,tt0019071,Emil Jannings,Emil Jannings,nm0417837,True,General Dolgorucki [Grand Duke Sergius Alexander],Best Actor
3,1,1928,Acting,ACTOR IN A LEADING ROLE,ACTOR,an0051250b,The Way of All Flesh,tt0019553,Emil Jannings,Emil Jannings,nm0417837,True,August Schilling,Best Actor
4,1,1928,Acting,ACTRESS IN A LEADING ROLE,ACTRESS,an0051255,A Ship Comes In,tt0018389,Louise Dresser,Louise Dresser,nm0237571,False,Mrs. Pleznik,Best Actress
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12009,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,N/A,N/A,N/A,N/A,"Dustin Brooks, Colin Decker",N/A,True,N/A,Other / Retired
12010,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,N/A,N/A,N/A,N/A,"Attila T. Áfra, Timo Aila",N/A,True,N/A,Other / Retired
12011,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,N/A,N/A,N/A,N/A,Mark Noel,N/A,True,N/A,Other / Retired
12012,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,N/A,N/A,N/A,N/A,"Su Tie, Bei Shimen, Zhao Yanchong",N/A,True,N/A,Other / Retired
12013,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,N/A,N/A,N/A,N/A,"Tabb Firchau, John Ellison, Steve Webb, David ...",N/A,True,N/A,Other / Retired

In [800]:
oscars.main_category.value_counts()

main_category
Other / Retired                    1726
Best Original Score                 818
Best Cinematography                 641
Best Production Design              624
Best Picture                        616
Best Film Editing                   603
Best Original Screenplay            550
Best Sound                          531
Best Live-Action Short Film         504
Best Actress                        484
Best Adapted Screenplay             482
Best Actor                          481
Best Original Song                  480
Best Director                       476
Best Costume Design                 454
Best Supporting Actor               445
Best Supporting Actress             445
Best Documentary Short Film         393
Best Documentary Feature Film       385
Best International Feature Film     352
Best Visual Effects                 281
Best Makeup & Hairstyling           138
Best Animated Feature Film          104
Name: count, dtype: int64

In [801]:
oscars.dtypes

ceremony               int64
award_year             int32
award_class           object
canonical_category    object
category              object
nom_id                object
film                  object
film_id               object
name                  object
nominees              object
nominee_ids           object
winner                  bool
detail                object
main_category         object
dtype: object

### decided to create column 'decade' for possible use in analysis

In [802]:
oscars['decade'] = (oscars['award_year'] // 10) * 10

In [803]:
oscars

,ceremony,award_year,award_class,canonical_category,category,nom_id,film,film_id,name,nominees,nominee_ids,winner,detail,main_category,decade
0,1,1928,Acting,ACTOR IN A LEADING ROLE,ACTOR,an0051251,The Noose,tt0019217,Richard Barthelmess,Richard Barthelmess,nm0001932,False,Nickie Elkins,Best Actor,1920
1,1,1928,Acting,ACTOR IN A LEADING ROLE,ACTOR,an0051252,The Patent Leather Kid,tt0018253,Richard Barthelmess,Richard Barthelmess,nm0001932,False,The Patent Leather Kid,Best Actor,1920
2,1,1928,Acting,ACTOR IN A LEADING ROLE,ACTOR,an0051250a,The Last Command,tt0019071,Emil Jannings,Emil Jannings,nm0417837,True,General Dolgorucki [Grand Duke Sergius Alexander],Best Actor,1920
3,1,1928,Acting,ACTOR IN A LEADING ROLE,ACTOR,an0051250b,The Way of All Flesh,tt0019553,Emil Jannings,Emil Jannings,nm0417837,True,August Schilling,Best Actor,1920
4,1,1928,Acting,ACTRESS IN A LEADING ROLE,ACTRESS,an0051255,A Ship Comes In,tt0018389,Louise Dresser,Louise Dresser,nm0237571,False,Mrs. Pleznik,Best Actress,1920
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12009,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,N/A,N/A,N/A,N/A,"Dustin Brooks, Colin Decker",N/A,True,N/A,Other / Retired,2020
12010,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,N/A,N/A,N/A,N/A,"Attila T. Áfra, Timo Aila",N/A,True,N/A,Other / Retired,2020
12011,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,N/A,N/A,N/A,N/A,Mark Noel,N/A,True,N/A,Other / Retired,2020
12012,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,N/A,N/A,N/A,N/A,"Su Tie, Bei Shimen, Zhao Yanchong",N/A,True,N/A,Other / Retired,2020
12013,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,N/A,N/A,N/A,N/A,"Tabb Firchau, John Ellison, Steve Webb, David ...",N/A,True,N/A,Other / Retired,2020

# Save transformed data

#### In order to see if the scripts I will write to carry out this cleaning/trasnforming in pipeline are correct, I will save a the csv to test_data to test they are the same.

In [804]:
oscars.to_csv('../tests/test_data/expected_oscars_cleaned.csv', index=False)